[package]
name = "mdcode"
version = "0.1.1"
edition = "2021"

[dependencies]
clap = { version = "4.1", features = ["derive"] }
git2 = "0.16"
chrono = "0.4"
walkdir = "2.3"
env_logger = "0.11"
log = "0.4"

[dev-dependencies]
tempfile = "3.5"
