name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Build release binary
        run: cargo build --release --locked

      - name: Package artifacts
        run: |
          mkdir -p dist
          cp target/release/mdcode dist/
          # Add README and license for completeness
          cp readme.md dist/ || true
          cp LICENSE dist/ || true
          tar -czf mdcode-${{ github.ref_name }}-linux-x86_64.tar.gz -C dist mdcode readme.md LICENSE || tar -czf mdcode-${{ github.ref_name }}-linux-x86_64.tar.gz -C dist mdcode

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            mdcode-${{ github.ref_name }}-linux-x86_64.tar.gz

